apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  # Dummy MySQL local installation credentials, by no means these are prod ready, just for testing purposes
  password: test1234

