apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  # dnsutils was used to resolve the local DNS for this service (mysql) that exposes a type of ClusterIP (no ingress)
  MYSQL_HOST: mysql.default.svc.cluster.local
  MYSQL_USER: auth_user
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
