# This file would never be pushed to git, is used for illustrative purposes
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MYSQL_PASSWORD: Auth123
  JWT_SECRET: sarcasm
type: Opaque
