apiVersion: v1
kind: Service
metadata:
  labels:
    app:
  name: mongodb-nodeport-svc
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000
  selector:
    app: mongodb
  type: NodePort
status:
  loadBalancer: {}
